[package]
name = "hello_work"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
eframe = "0.31.1"
egui_extras = { version = "0.31.1", features = ["gif"] }
image = { version = "0.25", features = ["gif"] }
rusqlite = { version = "0.35.0", features = ["bundled"] }
